### ISSUE TITLE
pymysql.err.ProgrammingError: (1146, "Table 'JSFuzzing.Table_Function' doesn't exist")

### ISSUE THREAD

**Issue by Qbtly** [NWU-NISL-Fuzzing/COMFUZZ#1]
**When I try to execute COMFUZZ according to Quick Run, I encountered the following error:**

```
~/COMFUZZ/COMFUZZ_Js/workline# python main.py --enrich_limit_num=10 --loop_times=5 --clean_project
Namespace(clean_project=True, enrich_limit_num=10, loop_times=5)
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    removeDB.run()
  File "/root/COMFUZZ/COMFUZZ_Js/workline/step2_init.py", line 56, in run
    self.table_Function.deleteAllFromTableFunction()
  File "/root/COMFUZZ/COMFUZZ_Js/workline/mysql_tools/Table_Operation.py", line 51, in deleteAllFromTableFunction
    return self.__table.deleteAll(sql)
  File "/root/COMFUZZ/COMFUZZ_Js/workline/mysql_tools/db_operation_base.py", line 113, in deleteAll
    recount = cur.execute(sql)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'JSFuzzing.Table_Function' doesn't exist")
```

**Can anyone tell me how to solve this problem？**

**Comment by ym-xie** [comment]
> **When I try to execute COMFUZZ according to Quick Run, I encountered the following error:**
> 
> ```
> ~/COMFUZZ/COMFUZZ_Js/workline# python main.py --enrich_limit_num=10 --loop_times=5 --clean_project
> Namespace(clean_project=True, enrich_limit_num=10, loop_times=5)
> Traceback (most recent call last):
>   File "main.py", line 31, in <module>
>     removeDB.run()
>   File "/root/COMFUZZ/COMFUZZ_Js/workline/step2_init.py", line 56, in run
>     self.table_Function.deleteAllFromTableFunction()
>   File "/root/COMFUZZ/COMFUZZ_Js/workline/mysql_tools/Table_Operation.py", line 51, in deleteAllFromTableFunction
>     return self.__table.deleteAll(sql)
>   File "/root/COMFUZZ/COMFUZZ_Js/workline/mysql_tools/db_operation_base.py", line 113, in deleteAll
>     recount = cur.execute(sql)
>   File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 148, in execute
>     result = self._query(query)
>   File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 310, in _query
>     conn.query(q)
>   File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 548, in query
>     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
>   File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 775, in _read_query_result
>     result.read()
>   File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1156, in read
>     first_packet = self.connection._read_packet()
>   File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 725, in _read_packet
>     packet.raise_for_error()
>   File "/usr/local/lib/python3.6/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
>     err.raise_mysql_exception(self._data)
>   File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
>     raise errorclass(errno, errval)
> pymysql.err.ProgrammingError: (1146, "Table 'JSFuzzing.Table_Function' doesn't exist")
> ```
> 
> **Can anyone tell me how to solve this problem？**

Hello, how did you solve this problem? I used the mysql image provided in the code repository, and the JS part did not have this table either.
